name: Deploy HTML to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      
      - name: Deploy to S3
        run: |
          BUCKET_NAME="${{ secrets.BUCKET_NAME }}"
          aws s3 sync portfolio/src "s3://${BUCKET_NAME}" --delete

